spring:
  security:
    oauth:
        resourceserver:
            jwt:
              issuer-uri: "http://127.0.0.1:9000"
        client:
            registration:
                client-app:
                    provider: spring
                    client-id: client-app
                    client-secret: 12345
                    authorization-grant-type: authorization_code
                    redirect-uri: "http://127.0.0.1:8080/authorized"
                    scope:
                      -openid
                      -profile
                      -read
                    client-name: client-app
            provider:
              spring:
                authorization-uri: "http://127.0.0.1:9000"
